{
 "title": "System",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "s21_diskIO",
     "legendFormat": "Количество записей ввода-вывода"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "s21_free_ram", "legendFormat": "Доступная оперативная память" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "s21_cpu_usage" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "s21_mem_free", "legendFormat": "Доступная память" },
    { "expr": "s21_mem_used", "legendFormat": "Занятая память" },
    { "expr": "s21_mem_cache", "legendFormat": "Вся память" }
   ]
  }
 ]
}